# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: monsters.fun
#######################################################
# GLOBAL CONTRACT DEFINITIONS
#######################################################
contracts:
  # ————————————————— 11124 contracts —————————————————
  - name: CreatureBoringFactory
    handler: src/EventHandlers.ts
    events:
      - event: event TokenCreated(address tokenAddress, string name, string symbol)

  - name: CreatureBoringToken
    handler: src/EventHandlers.ts
    events:
      - event: BattleStarted(address indexed opponent)
      - event: BattleEnded(address indexed winner, address indexed loser, uint256 transferredValue)
        field_selection:
          transaction_fields:
            - hash
      - event: Trade(address indexed trader, bool isBuy, uint256 amount, uint256 ethAmount, uint256 protocolFee)
        field_selection:
          transaction_fields:
            - hash
      - event: Transfer(address indexed from, address indexed to, uint256 value)
        field_selection:
          transaction_fields:
            - hash
      - event: WhitelistPurchase(address indexed buyer, uint256 amount, uint256 ethAmount)
        field_selection:
          transaction_fields:
            - hash
      - event: PriceUpdate(uint256 newPrice, uint256 tokenSupply, uint256 curveMultiplierValue)
        field_selection:
          transaction_fields:
            - hash
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Paused(address account)
      - event: Unpaused(address account)

  # ————————————————— 2741 contracts —————————————————
  - name: MonsterCapsule
    handler: src/EventHandlers.ts
    events:
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)

#######################################################
# MULTICHAIN SETTINGS
#######################################################
unordered_multichain_mode: true

networks:
  # ---------- ABS testnet ----------
  - id: 11124
    start_block: 8963740
    rpc: https://api.testnet.abs.xyz
    contracts:
      - name: CreatureBoringFactory
        address: "0x1Dc3f87AC2059919700e69FBcb93E92B0FeBbb18"
      - name: CreatureBoringToken

  # ---------- ABS mainnet ----------
  - id: 2741
    start_block: 9349083
    contracts:
      - name: MonsterCapsule
        address: "0x38272B362bcA267Dc8e9120087c93CefB86a69aC"