# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: monsters.fun
networks:
- id: 84532
  start_block: 22798903  
  contracts:
  - name: CreatureBoringFactory
    address:
    - 0xFf97F43223107d6BB1629e139F71154Be82Fa588
    handler: src/EventHandlers.ts
    events:
    - event: event ERC20Initialized(address indexed tokenAddress, string name, string symbol, uint256 initialSupply)
  - name: CreatureBoringToken    
    handler: src/EventHandlers.ts
    events:
    - event: BattleStarted(address indexed opponent)
    - event: BattleEnded(address indexed winner, address indexed loser, uint256 transferredValue)
      field_selection:  
        transaction_fields: 
        - "hash"   
    - event: Trade(address indexed trader, bool isBuy, uint256 amount, uint256 ethAmount, uint256 protocolFee)
      field_selection:  
        transaction_fields: 
        - "hash"         
    - event: Transfer(address indexed from, address indexed to, uint256 value)
      field_selection:  
        transaction_fields: 
        - "hash"         
    # - event: Approval(address indexed owner, address indexed spender, uint256 value)
    # - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    # - event: Paused(address account)
    # - event: Unpaused(address account)
    # - event: TokensMigrated(address indexed account, uint256 amount)
    # - event: WhitelistPurchase(address indexed buyer, uint256 amount)
